name: CI

on: [push, pull_request]

jobs:
  melodic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env:  {ROS_DISTRO: melodic, ROS_REPO: main}
